### ISSUE TITLE
Problem met when try to run retina_demo.py

### ISSUE THREAD

**Issue by iKaHibi** [neurokernel/retina#1]
Hello!
When I tried to run python retina_demo.py -c retina_default.cfg -v -1, It comes the problem:

Traceback (most recent call last):
  File "retina_demo.py", line 17, in <module>
    from retina.input_generator import RetinaInputGenerator
ImportError: No module named input_generator

I have already installed the neurokernel and neurokernel/retina.
I have no problem importing retina, but I have no idea where the input_generator is.

How can I solve this problem?
Thanks a lot!

**Comment by yiyin** [comment]
Hi @Teaine ,

Please use the [retina_worker_only_demo](https://github.com/neurokernel/retina/tree/master/examples/retina_worker_only_demo) instead. The retina_demo was deprecated.
To run the this, you will need to create a config file, e.g. `config.cfg` with the configuration, for example:
```ini
[General]
  dt = 1e-4
  log = 'none'
  steps = 1000

[Retina]
  screentype = 'Sphere'
  intype = 'Bar'

[InputType]
  [[Bar]]
    bar_width = 20
    speed = 300

[Screen]
  [[SphereScreen]]
    radius = 5
```
Please refer to [template_spec.cfg](https://github.com/neurokernel/retina/blob/master/examples/template_spec.cfg) for a complete list of options.

and then run 
```bash
python retina_worker_only_demo.py -c config.cfg
```

**Comment by iKaHibi** [comment]
Thank you!
I did not meet importing problem by running retina_worker_only_demo.py
